# Generated by Django 5.2.12 on 2026-03-21 12:03

from django.db import migrations, models


def normalize_gender(apps, schema_editor):
    Patient = apps.get_model('dental', 'Patient')
    Patient.objects.filter(gender='Male').update(gender='male')
    Patient.objects.filter(gender='Female').update(gender='female')


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_gender),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
