# Generated by Django 5.2.12 on 2026-03-21 12:42

from django.db import migrations, models

STATUS_MAP = {
    'Scheduled': 'scheduled',
    'Completed': 'completed',
    'Cancelled': 'cancelled',
    'No Show': 'no_show',
}


def normalize_status(apps, schema_editor):
    Appointment = apps.get_model('dental', 'Appointment')
    for old, new in STATUS_MAP.items():
        Appointment.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0002_gender_lowercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(normalize_status),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
    ]
