# Generated by Django 5.2.12 on 2026-03-21 13:05

from django.db import migrations, models


def normalize_invoice_status(apps, schema_editor):
    Invoice = apps.get_model('dental', 'Invoice')
    Invoice.objects.filter(status='Paid').update(status='paid')
    Invoice.objects.filter(status='Unpaid').update(status='unpaid')
    Invoice.objects.filter(status='Partial').update(status='partial')


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0003_appointment_notes_status'),
    ]

    operations = [
        migrations.RunPython(normalize_invoice_status),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='pending', max_length=20),
        ),
    ]
