# Generated by Django 5.2.12 on 2026-03-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0004_invoice_status_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='patient_treatment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='dental.patienttreatment'),
        ),
    ]
