# Generated by Django 5.2.12 on 2026-03-21 13:19

from django.db import migrations, models

METHOD_MAP = {
    'EVC Plus': 'evc_plus',
    'Cash': 'cash',
    'Card': 'card',
    'Bank Transfer': 'bank_transfer',
    'Other': 'other',
}


def normalize_payment_method(apps, schema_editor):
    Payment = apps.get_model('dental', 'Payment')
    for old, new in METHOD_MAP.items():
        Payment.objects.filter(method=old).update(method=new)


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0005_invoice_patient_treatment'),
    ]

    operations = [
        migrations.RunPython(normalize_payment_method),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('evc_plus', 'EVC Plus'), ('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=50),
        ),
    ]
