# Generated by Django 5.2.12 on 2026-03-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0006_payment_method_lowercase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('evc_plus', 'EVC Plus'), ('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=50),
        ),
    ]
