# Generated by Django 5.2.12 on 2026-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0007_payment_method_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
    ]
