# Generated by Django 5.2.12 on 2026-03-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0010_user_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall_type', models.CharField(choices=[('monthly', 'Monthly'), ('cleaning', 'Cleaning'), ('checkup', 'Checkup')], help_text='Type of follow-up', max_length=20)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Specific day patient must come (1-31)')),
                ('interval_months', models.PositiveIntegerField(default=6, help_text='How often patient returns (in months)')),
                ('start_date', models.DateField(help_text='First visit date')),
                ('next_visit', models.DateField(blank=True, help_text='Automatically calculated next visit', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dentist', models.ForeignKey(help_text='Responsible dentist', on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='dental.dentist')),
                ('patient', models.ForeignKey(help_text='Which patient must return', on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='dental.patient')),
                ('treatment', models.ForeignKey(blank=True, help_text='Treatment related to the recall', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='dental.treatment')),
            ],
            options={
                'verbose_name': 'Patient Recall',
                'verbose_name_plural': 'Patient Recalls',
                'ordering': ['-next_visit', '-created_at'],
            },
        ),
    ]
