# Generated by Django 5.2.12 on 2026-03-23 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0011_patient_recall'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(help_text='Date the reminder is scheduled for')),
                ('method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('sent', models.BooleanField(default=False, help_text='Whether the notification was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(help_text='Patient to notify', on_delete=django.db.models.deletion.CASCADE, related_name='recall_notifications', to='dental.patient')),
                ('recall', models.ForeignKey(help_text='Related recall', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dental.patientrecall')),
            ],
            options={
                'verbose_name': 'Recall Notification',
                'verbose_name_plural': 'Recall Notifications',
                'ordering': ['-reminder_date', '-created_at'],
            },
        ),
    ]
